name: DL
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - h5py=2.9.0
  - numpy=1.16.4
  - python=3.7.4
  - matplotlib=3.1.1
  - scipy=1.3.1
  - pandas=0.25.1
  - scikit-learn=0.21.3
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pip=19.2.3
  - pip:
    - opencv-python==4.1.1.26
    - skorch==0.6.0
    - graphviz==0.13
    - pydot==1.4.1
    #  - tensorflow-gpu==2.0.0
    - tensorflow==2.0.0
